# Generated by Django 2.1.2 on 2018-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Windforecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('runtime_date', models.DateField()),
                ('wind_max', models.FloatField()),
                ('wind_average', models.FloatField()),
            ],
        ),
    ]
