# Generated by Django 2.1.2 on 2018-11-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_windforecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windforecast',
            old_name='forecast_date',
            new_name='forecast_time',
        ),
        migrations.RenameField(
            model_name='windforecast',
            old_name='runtime_date',
            new_name='runtime',
        ),
    ]
