# Generated by Django 2.1.2 on 2018-11-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181126_1920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='windforecast',
            unique_together={('forecast_time', 'runtime')},
        ),
    ]
