# Generated by Django 2.1.2 on 2018-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181126_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windforecast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
