# Generated by Django 2.1.2 on 2018-11-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181126_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windforecast',
            name='runtime',
            field=models.DateField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='windforecast',
            unique_together=set(),
        ),
    ]
