# Generated by Django 2.1.2 on 2018-11-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181126_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windforecast',
            name='forecast_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='windforecast',
            name='runtime',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='windforecast',
            unique_together={('forecast_time', 'runtime')},
        ),
    ]
