# Generated by Django 2.1.2 on 2018-11-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181126_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windforecast',
            name='runtime',
            field=models.DateTimeField(),
        ),
    ]
