# Generated by Django 2.1.2 on 2018-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181126_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('runtime', models.DateTimeField(unique=True)),
                ('wind_max', models.FloatField()),
                ('wind_average', models.FloatField()),
            ],
        ),
    ]
