# Generated by Django 2.1.2 on 2018-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_windmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windmeasurement',
            name='runtime',
            field=models.DateTimeField(),
        ),
    ]
