# Generated by Django 2.1.2 on 2018-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20181130_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='windforecast',
            name='wind_angle',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
